// Package gimage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package gimage

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8x8/XLbtpr3rWB4embkHEqiZCuN1cm8oySOoyZNXTtpe6bJa0EkRCEhARYAbasdz+xF",
	"7BXulew8+CBBkXLkprvrf2KJAIEHzxd+z4fyZxDzvOCMMCWD6Z+BILLgTBL95RlOzsnvJZEKvsWcKcL0",
	"R1wUGY2xopwNP0nO4Bm5wXmRETMzIcH0KIrCgAjBRTCFpZBbKwxyIiVOSTANfqGJWqO8lAotCSq4pIpe",
	"keA2DGS8JjmG5b4RZBVMg38Ma1KHZlQOT2D9c0t0cHt7GwYJkbGgBRAXTIM5u8IZTZAwm6MCC5wTRYSE",
	"TeZMEcFwdmLIvP8hJ/4h3WrogogrIpBZ1T/uS0wzkiDFUSF4TKRENIeRv/O8lgZpaDC03VYbWMGqeP1j",
	"QQQ2b/0ZFIIXRChqBG+Imv65tfYzLMnjoz5hcPbEkI64QBeH6DPZBGHNHrOCHBZrrvjgU5EGYaA2BYxI",
	"JShL4cTcJ6C5U0Ub0m+FAWFlHkx/A/2kf8ADGeMM/saCF/CH54UgUuqP7IoIFXz06anea1GhFUKfGicJ",
	"hT1xduZxQ4mShLvI68uCxHRFY1+vQl9N1oSmaxVMH4OiXIO2B9MnUXRbUcKXn0istIRAR6kgCRy0Zk5o",
	"xVGR+rH1bmgk6hlrU54xzrIljj9fliLrYrY5NbomyzXnn9H78zdoxQUCpmZEi4FxBcd0FNWMXStVyOlw",
	"mG9wUQxing/tKkEYrLjIsQqmQSnonQog20S9oVIhvkL1HG01RMCiwBNFjNTuspYtPb8NgxzfzM2bIxBI",
	"Tpn7WtGHhcCb3fK4k//WLlsCWMLwJU3a53zP6O8lQXoCoglhwGciGjzWg/3R+PBo8vjbJ8dRFy8FkWWm",
	"Ohh5bga0QAmO16ihWftwcQ7qV/ucbUaFgVRYlbLLX8ChrKejLEV2Ym3O9Zi14YwokoDqaEfZtGF/vHV+",
	"s3S3goM+K47iNYk/W07XlFTLD/XI8MvMvu2Q/3Prf3aaoLOFbdreYZEShcww6nFriyHKMWUKUyYRFzSl",
	"YJ90BXaIrM8hyYHHSeNjPxUE/hSan9dkWTQ5uMMR/1V331ro9xJnVG3MUitcZiqYPplse0/HK/Ar9g3U",
	"G/XBINGapmsi0FO0JEoRceBLCFbK8Q3N4cTOfO23ihjKFEmJsCahVfay5r3j1lIfDa6RQ60yH7uE7Ju/",
	"YdHHTsnr62an4P825n7VccJAaUW73KWHL4iEsyJeqqJ0+uhbKjP65WlZSldOy8JA0dXK/AnCYJlvKZ6b",
	"tAePtynt5LngxU6Guxt3+4TwEjKDiDJU0BuSNTzA4y+r1EMRpgUSnUfUY90nfPLlE960V/0VxZyLhDKs",
	"CFzJihf9jKwUirlgzauqaZVR1wab9gb//hs32KFTNwHs7BgXOiXpUq4mxG5jKY37t4/w6t27M3upID3D",
	"o1kHQm1GEBdzNFfS21ewt7KgZgDVUogqxGjbtTIxh94OuXn+0i5EMmpbWf4et94pYYAlyE5bxHBXqUuN",
	"N9q0zfQo0qMan5wSEC06/BfCLEGngn9GAD4oIwPzDWeSIxzHpFASjaejEI2m4xCNjgeT6XGIjqfwKUTj",
	"yHwbR6FeCZeKDxpnHj2eHnfxMRW8ZAl88e+wFc5kKwg4YXiZEXTKeZoRdEGwiNeoen/rPDlPSCYH6BnN",
	"QBgFEUiaN34vidiAubrwA6CKWhOY0zciiblUDfItPZb6JecZwazyT5c61Glx+y2G0NpKWRDJsxJGBh6V",
	"QwRXGbnprzIs14+maPQ6ROPXIfiyo9eDhkTQEP1kLm+YBjPGrxFn2Qb1clxotH4zm3sbHQy862T0OgiD",
	"Mfxz9Lp5VeiHbYjCilJdmqiyC+OuiCAstqeTVfSi8wk6tiHAXJYO0Bse4wwVWK0l6p29PR1+f3ZyOvyF",
	"LM8O9Gs4ywCyXtGECPldh9oV5TKjMXKBD0RLcoCe40JO9eynh6Fj6XgwQS+Bld6zQ3Qm+NPRqH4wGNlJ",
	"o6OGlH8LhiovhvEaCxwrIgbmDtYPIZozuqaj648elG/7hjrmOWqDd62ZHbY5NzoLciyldgsoNeZuQ0Ar",
	"yVSfoj8eTIzW9J3LtQOH/ULw1sPBaGu2r3hbX/srrJ1e41mZKYEDbbCf9SKUkXqX1sO+g6YNXesksZ0h",
	"EDwvuqA7uVHIe6SvrrWzMMUdv5reFiNZMkkU4ldEoJyXBuUHWk5vCEvhYh9H9p5zD0b7YYgmgWcC7AJQ",
	"nZvaxnUdaKOm1T7rCrcI6QhmzzFLeI5gUCuMIIXgSRlTcJQ2QkW9yIzpuQ2AfzT2cgaUKU3X3WiidnXW",
	"VQejaHx0A/8ErdSYlktCc8KkTij0fpm/ePfq5tXJ/PTVu4Pm/eCtUmAIRWCF///hQ/KvG/jnm+4YdJN1",
	"OF6zrx4cYiLVmiga+9B6zRUXBGdUmgEsVPWR0Zw0hdKa3ob6a8o+U5ZeZuSqy7bPCZacwSWVkEKtd1xV",
	"r1wolnNBUJFhpl9ZkhV8r33BAM1TxkHLlhvEFbxT+U/f5WtBYtCmjF/rrGhCyxywGE3XzSOaCa1zlZKI",
	"O9JXhCV9mOKlUYxHX4IDyzmjisNSqAduegi3E9xXB01koAjDTPWPxl+MV6xf6MKQrwjO1B35IFzQO1KO",
	"dSyArzDNAGYEYcC4uow5W9G0FDoHUrJ6uCtIaLLpwoBTvkKzuU4O05hs5SqNOwQf5W1rvG7jYRcU3JUD",
	"+vGKCLhS7Y7tFNBas2qjrTUVOLFHc48belHPbR32igjZmUqenc2RG/TXigajwWg/mNtMgO2d2pk38bRn",
	"wawzDbMrcDXr3BW5gqP62nA1wQqjHtiLzEFgBkk1vSL9+dmP59fR69OUz2az2duL9+uT9yl8PIF/nj2f",
	"/XswGHTHJwrDDncp/RcUeFa9hqrVuhTx8BJi7tahTSxukOEaU+3LvKRuR/GizgH28TIe7JCavSO7Ll9J",
	"U0YSdHGoM+qatxkWqUOpITJx1+MI5ZQddKbVU4NepOICp2QgDwc4x39whq+lTrZ7pDoi/9+v/Vn+R98I",
	"4kspeLg/L5cb1YWqrf7SjCCYBqpnZnqETsZH4ydPOq7ttjLuyFmYXe5IWnQrd5ednusiz70TQzYF++XU",
	"kJd7/J9LFd2vhna/PJJfUrCD+6aWLJO+mFy6B492pGr2SNFcxDjbLecVjlVXZgXe0pG5Hke9aDBBT9Ea",
	"Z6sQjQcReooSXi4z0rDEaDDxtNtMCBrn9CHqIKrPycp8+ZCyhjvYbbn1sasgKUlcCqo2F/Ga5Ia5s4K+",
	"JptZ2aUjcNU6H4tLtQYUZkqGqFchF1AemHiKFbnGG2A2ZeZuT3Suj+EcyPi1Pzub91/7jMB6b1P1pmzF",
	"XcEex5oV9sVTw8iLsii4gItXu2fPo6p1udTOExeCSEytk+24ceb9gl8TUQmnBr06reRVtuBEbu5y45JC",
	"BlSH6GeNodBsbtJRgDwBgg4+sA/sH/9ALwlWpSDyA+ujR49mc2R84mm126NHU/RcEKzqBIfgOVIQgJZ6",
	"/+2EQzPd0M41oCuKHVk9P7BGwBOi5IFO+jhK0awUXGBDoKHurDo8UGdcb4h0WT5EseBFiFxR3pza1uXt",
	"CcxSpkJYVWglLGUXRnmZKVpk1ZFjzuJSCMJUtjFvv8zIjQ4tHTaD1y889IKwRMYwwsbNC88vDvVRzRX9",
	"/vyNtMKYNRT3A3vu9gx1cA+CLiWRiLArKjjLCVN92CPZUvkBesl1JJSUsdaYhBQZ38B8GX5gOEmQs5ct",
	"WwHReBYy+ADANaMxsejT6vkP83f7K/dwmfHlMMeUDd/Mn5+8vTjRKJ6qzDOZ2dk88JB0MBqMB48f20o9",
	"wwWEBoeDaHBoguK1dgimYKq9MJedSYgvixNdU7VGCV3pNJ7ycJk2kUePrDGTxBuaPnoEarAwrR0Lp4NI",
	"cS/G1zO0Ui6mSF8bYJ7G5+kx0NQFWBcvkCCpFjk8tqoLQ/ajIdLmkewkrdF6jtFt45eB5lmW+b0LGEJo",
	"wwnwJkz3i2QZyZz9cpRywUtFGZFG4tXb88TV0i0vA+PJiVTPeLLZv21JyyunNyS5bLZeyDLPsdiAUjkp",
	"NaDxFc5KrXr+a79Vtc0GUhlZqOJ199TdN3Wzza6+mNuwe9mxxd/+sl7TT71wdVfbmmNVk34y2bn4YQfN",
	"trGoTfEo8kg2X250dmoTTKPb24+3t3t3czW6dm6bN7QSJfGufE3COIr2kPa99t7dSdbq3qj7L27D4MiQ",
	"0rVDRfLQayC8DYPJPq80O/I0Kyvl3OFKdMk4BY00NAcf4bVhpR07XVNl2ZjVSVtBkjL2wx5t9g6+6JKP",
	"VSnrm2wVBEmiFGVp5Zd0R8Niiqr6Qt3ssNXl4AbsJSX05gewyAuT1pyixZPJAvVSzhO0xBlmsRk/JzHP",
	"c8ISksCcqH8cLTT8uibLEC2Oo/7xxDwoBGWqw684HswtHPzrjgUOdel1gNRye0XTynFWoMDkYyrPUpll",
	"nWIwEWy14vGkAwA7uAsSvybLS14omtuccE3Aj/apY42/cbWScQFb7kELpO+HYA1/srelb/cH/S8b+1YL",
	"V0fbqC00GipJgmQZg62tyizb/F/Ze2WfdWeIMfMae1a2bno+7zB1c0FXlr4k6poQ5oEOowhtxGGfO7Mu",
	"WLqYojMulPYFb4m65uIzOhW4WNNYop40b0qkBGaywIKweKOtdfGpSBch/CGpdQyol3EpNyFivGN+SleL",
	"ab205lW8xiwlAC51w1hGcwpUxjzjQoYdi8A9uJgi7YF6OU+IYGAD9lyhSfcRoZ2dNK8ouloBoUrv/w6n",
	"KUlsUPIS/OJLC3P6aLHMYfFnVOW46HQvmu9f710UvwT7a5i1E6rimpd7uZO2B6lTIc0OKe0QdJ6JX2os",
	"sWtv4Gzn3n7+xmYPt7bQ697LjTSazR6qF9FEPhgn4oWdXnfLTlcCuG+3H4E4ASNBYoVZWmZY2KjBROTO",
	"vVgn8rxqa6rcxw3Y1QasqtnkhPhKR81uuV4URojKuheKr8zS1qgBfsJSBpUupuhFXddsLtVllYIXX2+S",
	"MQG2XzqGeSyHzc2opcE3jwby77QVc9HWQYEG2Lrza6P/3sdgvE7BB2otghfFQ7EVEJyHhK3odtpK1eCw",
	"015chxhYxmzujFCbiklf+f0TLhTelTvzElLWwH7QtWo0c6VJa2Xm3SladDenLFDvm2gQHR6b8slBWE3c",
	"6kuxE48m/W+iwWgyGlreUJfn87qbvEXqdhKzwOjwCBYYH5n3Q8RMK9bRa23M1QmnaOGn4haoZ2rkyBX0",
	"Q2T7HGC3VosMzDc19uqF1jzdNrMwEUg9C/3Xf/ynbnwqJbkzVegE/twYyHdoX/Z8V21mew6usKBEwiST",
	"cARGOOGC4FodPFYWY09mO7t87FxNV/Tt0PlN0BhnkBbDVH7ZoIDF1MIcXQ2tMvPMZhFNDc8msD6UUXQY",
	"o8lo/PqZccomFgF0uF37M4U+eNkU+0pFpFcQdGsedPhqZ0Ff769xcgWBY9J01jP71MS55vcHjZyPbRDb",
	"3ejl+qOCValKobtSUAyhnl5xlW108gALGdwRwLmWoqOxa+pp9ODY1prt5hftvqjrX6gPdaGfNRvWqgNV",
	"9O5qxbrH/bLdAfu33TG+4CxCbZzQFI/qxq6eV7U/6IxvDQKts1jjo7ALJu8q7MPf1cv44nv48OJ9dvLT",
	"z+dH4/zt53/9cPzTi+vZi3V6Ovvl0/kxvtavfH/+fnIiPn+fpunTp0Gz0uyqxlUSbXx02yile5I0BlSf",
	"08vj739O1xRwZ2nfbf9Xiu/NxRoleP/g4+j429FkvHXyvbVtT0jhvPTDABUVBPAuf331Wzus8UVd8LL4",
	"wvT7mNakLjCuf9A1O5sjM9H0ehssQHWyqdntpEHDOVGlYNI16/PVtEYMeq0eBfhMdA8ZziSqe66at/WX",
	"Jla1szvntfy9aR3TRwu+2nPgLLus+7aafj/L4LgSNZq9nDW5BrXOljC4ePfqEnNNYV7jVru6dOu6gi85",
	"y7Yyh1YseuCe1LXa5SoSt0b2pnNvM93q/uuw0wvbDUclcls2jcYsYX6y6FmIeWytw1ZVdmJvWw/zk9vk",
	"BseuiQOMxfa8GOANmNAhKPQGs/gPLsHxgjpRllrIPWf178McetrZUAaDrvEK7L4Q5IpyMDun8x0WYOj+",
	"erxjrs1L/dOBplpZzlhQV7Wg3x2h7tv7dkeGqVHngvtmN20Xh7vpGkVP2qFz55V2B9xyN9Dx+D7xdLPF",
	"6mFG1MYuHsblZ6VZGWD1/wXUJeq7AmzzvxzstHBT0K5z2huEXXHMNROYUre13RNrHS7oiQaThW2BMrWu",
	"3iT6p4llxoNoUXVE2cFx5EajwVi/+XuJhbK5Y9QbT/7ZdaNpKr/enA0p1Y+bPIiouaA4AvoakNA2go13",
	"WvEui/WqSsCcuzaddO+p+8Z2ZoLvYXGNXreHaXBaSx+GvRmxVOZgpbHLwnSLm4CrXrcztBpXXOuOhoWC",
	"FBmObT14w0vhN+lAkHLQaseBWX1c0D5NBuSGxKUi8HVQyj7BUvVHWwFFITjgkdb/haF/spaQK5LxIidM",
	"od7F7AeUwePmptPhUD9dc6mmh1EUBbcfq8P/uX97W92G52HyNmFG/F6LQKNrxK7gsby9QqvJoGsFU9Vv",
	"v+yDJA1nqh8X2BctXLr9ePvfAQAA///qYwKC6EgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
