// Package gimage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package gimage

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8x8+3Lbtrb3q2DY7omTUlfb2bH2ZL5REsdRk6aunbTd0+SzIHKJQkICLADaVjueOQ9x",
	"nvA8yZmFCy8i5chNzzn+J7IIEFhYN6zLT/kziESWCw5cq2DyZyBB5YIrMF+e0fgMfi9AafwWCa6Bmz9p",
	"nqcsopoJPvikBMdncE2zPAU7M4ZgcjAchgFIKWQwwaWIXysMMlCKJhBMgl9YrFckK5QmCyC5UEyzSwhu",
	"wkBFK8goLvethGUwCb4ZVKQO7KgaHOP6Z47o4ObmJgxiUJFkORIXTIIZv6Qpi4m0m5OcSpqBBqlwkxnX",
	"IDlNjy2Zdz/kYf2QfjVyDvISJLGr1o/7krIUYqIFyaWIQCnCMhz5O8/raFCWBkvbTbmBE6yOVj/mIKl9",
	"688glyIHqZkVvCVq8ufG2s+ogscHPeB49tiSToQk5/vkM6yDsGKPXUEN8pXQov8pT4Iw0OscR5SWjCd4",
	"YlEnoLlTSRsxb4UB8CILJr+hfrI/8IGKaIqfkRQ5fogsl6CU+ZNfgtTBxzo95XstKoxCmFPTOGa4J01P",
	"a9zQsoBwG3k9lUPEliyq61VYV5MVsGSlg8ljVJQr1PZg8mQ4vCkpEYtPEGkjIdRRJiHGg1bMCZ04SlI/",
	"tt4NrURrxtqUZ0TTdEGjzxeFTLuYbU9NrmCxEuIzeX/2hiyFJMjUFIwYuNB4TE9RxdiV1rmaDAbZmuZ5",
	"PxLZwK0ShMFSyIzqYBIUkt2qAKpN1BumNBFLUs0xVgMSF0WeaLBSu81aNvT8Jgwyej2zb45QIBnj/mtJ",
	"H5WSrrfL41b+O7tsCWCBwxcsbp/zPWe/F0DMBMJi4MhnkA0em8HeaLx/cPj4n0+Ohl28lKCKVHcw8swO",
	"GIECjVakoVm7cHGG6lf5nE1GhYHSVBeqy1/goZynYzwhbmJlztWYs+EUNMSoOsZRNm24Pt46v126W8FR",
	"n7Ug0Qqiz47TFSXl8gMzMvgys2865P/c+Z+tJuhtYZO2d1QmoIkdJnvC2WJIMsq4powrIiRLGNonW6Id",
	"EudzIH5Y46T1sZ9ywI/c8PMKFnmTg1sc8V91962Ffi9oyvTaLrWkRaqDyZPDTe/peYV+xb1B9kY9NEiy",
	"YskKJHlKFqA1yId1CeFKGb1mGZ7Ym6/7VhLDuIYEpDMJo7IXFe89txbmaHiN7BuV+dgl5Lr5WxZ97JS8",
	"uW62Cv5vY+5XHScMtFG0i216+AIUnpWIQueF18e6pXKrXzUtS9jSa1kYaLZc2o8gDBbZhuL5STvweJPS",
	"Tp5LkW9luL9xN0+ILxE7SBgnObuGtOEBHn9Zpe6LMF0g0XlEM9Z9widfPuF1e9VfSSSEjBmnGvBK1iLv",
	"pbDUJBKSN6+qplUOuzZYtzf499+4wRadug5wZ8+40CtJl3I1Q+x2LGXi/s0jvHr37tRdKsTMqNFsEqE2",
	"I8DnHM2VzPZl2FtaUDOBailEmWK07VrbnMNsR/y8+tI+RbJqW1r+DrfeCXCMJWCrLVK8q/SFiTfatE3N",
	"KDGjJj45ARQt2SenUpA9mppUBhNCvL4xgH/YJ8f9pB+SB6PJ6AF+PJ4c4efRZPQYPw8m+/ixPzl40Dgj",
	"zuviWyJFwWP8Ur+zljRVraD/mNNFCuREiCQFcg5URitSvt+g/zuSiRhS1SfPWIrMz0ESZd/4vQC5RvP0",
	"6QaeTa8A5/SsCCKhdL9OvqPHUb8QIgXKS390YVKbFnffWs7ZJSUokRZmuxajBU/XfXJe5LmQWpEHo9fI",
	"wjH+KyR5cPD6gXnHSaLIMfViPOnXbofR6yAMxvjPweum5zcP2xEHzwt9YZPEjthfRDQlS5YCyalemchf",
	"whIk8MgdSJUJiikZmPQFkJ88IXtvKRfkGeWUU6L0OkW1OX17Mvj+9Phk8AssTt2RT0H2jKBIRHNFep4t",
	"4/4heZlStXq6HzZY9XQ0qh70R27S6KAhrN+Cgc7yQbSikkYaZN9eneYhJmFWZUxS/LEWgbdNukpVDtox",
	"t6G7w6RmVvWQZYUy1kwSa6Uuc3MSS8wpeuP+YW+Jp+h5T+kG9nu5FK2H/dHGbAx94No+3PjaW1LjqxrP",
	"ilRLGoQBzegfgve5uKS9iPJLqnqXowkG24kUn83yjEO1f+thz8eaDW3rJL7FWQ6J0eWLXIos7wgVjlPI",
	"MAVCLtJLgb6RGxv1S1Y75iDyFEKi4VqH5IpqkBmVmP1m9PoN8ATv6dGwdgXUSg9btn8H15rUHpk70e+O",
	"NDmJNimhRBVcgSbiEiTJRGHThyYl46G7QEvSdgtOmgSeGmvEcNFPbQeMHWFMRat71pXHAXRkyWeUxyIj",
	"OGhUWkIuRVxEDD2yS33J3tCOmbmNzOFgXCtGMK4NXbeHKZVPdXdCMBqOD67xn6BVczNyiVkGXJlKxd4v",
	"sxfvXl2/Op6dvHr3sHkR1VbJKeY4uML///Ah/u4a//m2O7ldpx0e3u5rBgcUlF6BZlE9Zl8JLSTQlCk7",
	"QKUu/+Qsg6ZQWtPbOcSK8c+MJxcpXHZ5nzOgSnD0wTHkerXlTnzlc7xMSCB5Srl5ZQFL/F55qz6ZJVyg",
	"li3WRGh8J5fiksUgVf3yMYKkqE2puDLl1pgVGQZ5LFk1j2gn3J6GOKvsCg1fAU31LWUemrNbKolViE8v",
	"KUsxmgjCgAt9EQm+ZEkhTWmj4NVwV+zfZPm5jTnFkkxnpubLItgoQVqniB6itq31yo2HXRHettLOj5cg",
	"aZr6HduVnZVh1drYSiJp7I7mHzekUs1tHfYSpOqsEE9PZ8QP1tca9kf90W7Ra7OutXPFZtYMk2v2wzur",
	"K9vyUbvObQkpuomvzUJjqinZQ0NUGQrMRk9Nn8R+fvbj2dXw9UkiptPp9O35+9Xx+wT/PMZ/nj2f/rvf",
	"73enHZriDrcp/RcUeFq+RsrVuhRx/wJT6dahbYpto8EVZcaT1Gq1HT2JqrTXo4uov0Vq7obquvoUSzjE",
	"mNy/P3tjeZtSmfjINCQ2nXo8JBnjDzur5YmNYZQWkibQV/t9GxDRK2Vq6DVSPZH/79feNPujZwXxpco6",
	"3l4Xi7Xuiq6d/mJ0jdNQ9ezMGqGH44Pxkycdl2ZbGbeUIuwut9QiupW7y07PTO/mzvUeV1n9csWnVlL8",
	"n6sA3a01drfyUL1T4AZ3rRg5Jn2xZnQHHm2pwOxQeTmPaLpdzksa6a6CyblNR4kdJ3vD/iF5SlY0XYZk",
	"3B+SpyQWxSKFhiUO+4c17bYTgsY56wFif1idkxfZ4j4VA7ew23HrY1efUUFUSKbX59EKMsvcac5ew3pa",
	"dOkIXrXex9JCr4Br1wkke2XkgsqDE0+ohiu6RmYzbu/22JTwOM2QjF9709NZ73WdEdTsbZvZjC+F78PT",
	"yLDCvXhiGenKFBhMoHuueVS9KhbGedJcgqLMOdmOG2fWy8UVyFI4VchJKI/rDSs8kZ+7WPvajw1pQ/Kz",
	"iaHIdBaa96a/nJNnEEsRfe5/4B/4N9+Ql0B1IUF94D3y6NF0RqxbPCk3fPRoQp5LoLqqa0iRmWySFIaE",
	"zZpEsyLRLkeQS0Y9ZXv13JsgW0Crh6asUyOWvBWXlDw3Wbgl1FJ5WvIBqbReOCSm8R6SSIo8JL7tbhng",
	"Ou/uJHYp2wMse7AKl3ILk6xINcvT8uiR4FEhJXCdru3bL1O4NjmeD9Pw9fNaIEOoItZGwsYljM/P982R",
	"7W39/uyNckKZNnT4A3/u9wxNlo0yLxQoAvySScEz4LqHe8Qb2t8nL4VJSeIiMsoTQ56KtakchB84jWPi",
	"TWfDbFBENWPpf8AYNmURuEDUqfwPs3e76/lgkYrFIKOMD97Mnh+/PT82AT3Tac16pqezoBZUB6P+uP/4",
	"sevFc5pjlrDfH/b3bXa6Mr7BtkSNQxaqsxrwZXGSK6ZXJGZLU8XTtRDNmMqjR86uIa4NTR49QjWYW/DG",
	"3Osg0aKWbJsZRinnE2JuELRU6/7MGGrqHK1M5ERCYkSOj53q4pD70xLpCktuktFoM8fqtnXRSPM0Tevo",
	"BIq5rOUEmHpRTjFDgtTbsSCJkKLQjIOyEi/fnsW+W+54GVinDko/E/F6d2CSkVfGriG+aIIrVJFlVK5R",
	"qbyUGlHyJU0Lo3r1134ru5eNoGXkopYafqfC11Rwmm3Il5uwe9mxC8Xry9ZgPdXC5bXtuopl1/nJ4dbF",
	"9ztodtChNsW2XOdItl+uTZloHUyGNzcfb252xms1cDk3zctaywJqt78hYTwc7iDtO+29HSvWwmdUCIub",
	"MDiwpHTtUJI8qEEEb8LgcJdXmpg7w8pSObe4EtMUTlAjLc3BR3xtUGrHVtdUWjblVfVUQlxE9QzImL2P",
	"ZEyTx6mU800/OZCCAq0ZT0q/ZDAL8wmp+golnGEDx+AH3CUlzeYPcZEXtr44IfMnh3OylwgRkwVNKY/s",
	"+BlEIsuAxxDjnGHvaDg3kdgVLEIyPxr2jg7tg1wyrjv8iufBzEWGf92x4KEuahiPSm6vWFI6zjIosKWZ",
	"0rOUZllVG2wyW654dNgRC/vIFyV+BYsLkWuWueJsRcCP7qlnTX3jciXrAjbcgxFIr56NNfzJzpa+iQD6",
	"Xzb2DZBWBzDUtRYtlRATVURoa8siTdf/V/Ze2meF/bBmXsWepa1bVOctpm4v6NLSF6CvAHgt6LCK0I44",
	"3HNv1jlP5hNyKqQ2vuAt6CshP5MTSfMVixTZU75VqiXlKqcSeLQ21jr/lCfzED8gcY6B7KVCqXVIuOiY",
	"n7DlfFItbXgVrShPAINLAwlLWcaQykikQqqwYxG8B+cTYjzQXiZikBxtwJ0rtJU/kMbZKfuKZsslEqrN",
	"/u9okkDskpOX6BdfujCnR+aLDBd/xnRG8073Yvj+9d5Fiwu0v4ZZe6FqYXi5kztpe5CqKtLEQBmHYEpO",
	"4sLEEtv2Rs527l0v5bhC4sYWZt07uZEGnOy+ehFD5L1xIrW0s4Zf2epKMO7b7kcwT6BEQqQpT4qUSpc1",
	"2MzcuxfnRJ6XwKXSfVyjXa3RqpowJiKWJmv2y+0NwyFhqkI7iaVd2hk1hp+4lI1K5xPyomowNpfqskop",
	"8q83yQiQ7ReeYTWW4+Z21NFQN49G5N9pK/airZICE2AbbNfafN7FYGpYwHtqLVLk+X2xFRRcLRJ2ottq",
	"KyXSYKu9eAwYWsZ05o3QmIotY9WBDD4V3lZGaxamnI39YPrGZOoblc7Q7OsTMu+GsszJ3rfD/nD/yDZT",
	"HoblxA0Ui5t4cNj7dtgfHY4Gjj3MV/0q7FR9kQpiYhcY7R/gAuMD+37o8VIHr409l4eckHm9Kjcne7Zf",
	"TXxzPSQOc4C7tQA1ON/2u8sXWvMMyGZuk5BqFvmv//hPQtPU4IJuqxp6mT+3NvIvsit7/lVu5vr/l1Qy",
	"UDjJ1h6RETX5Tsh8Cw7IywT3HD4ZeLeI2uDtzYUopdu1l/x84qIY0/csa/DcFQltt87Vpz4Uw+F+RA5H",
	"49fPrM+1qQYGf5tdPtvSw5dtW6/QoGqtP7/mww5X7A3k690xjS8xL4ybvnjqnto01v6AoFHScVCx7ZCv",
	"Fh6qgWoKKqBSsCx0IQ08hESY6pktl+naFA+oVMEtCZzH9hyMPbqmAYZxGJdNFIpxX8xDGapTn5tnTWxb",
	"eeKS3m2YqDvcL5sY17/tjqlL1kWojRPaPlKFsNqrNfAfdua3NgKtqljjg7ArTN7W48fP5cvo/Hv848X7",
	"9Pinn88Oxtnbz9/9cPTTi6vpi1VyMv3l09kRvTKvfH/2/vBYfv4+SZKnT4Nm09k3kMsi2vjgptFVr0nS",
	"Wlh1zlodf/dzenzArV1+v/1f6cM3F2t04+sHHw+P/jk6HG+cfGdt2zGk8C76fgQVZQhQu/zN1e/ssIov",
	"qsaXiy8s9MeilLqCcfOTrenpjNiJps3kEEvMFJuawCcTMZyBLiRXHo4vlpMqXDBr7TEMn8H82I6milTw",
	"q+ZVffvElqO36DBDcvDVHoGm6UUFzWo6/DTFYyjSwHN5K/EYtIW9YzdgX3fAgnnoVw2e1W4c3fglLwRP",
	"N4qCjuNm4FYCWxC426ncmL4zqTsb4QbMr8MKzx3sjSnit2yahF3C/uSwpv/2sdN91zPZGlm7ble9dA3X",
	"NPJoDTQFB26xYTWGex4WTd5QHv0hFLpVVCrGExdNz3j1+y4fPG1FjuGgR1ihVecSLplAo/Ka32EHlu6v",
	"D3fspXhhfivQ1CzHGRfTlVj02/PPXUFut9SPGl0svE2203a+v52u0fBJOzHuvLBuCab8/XI0vku23MRS",
	"3c982drF/bjanDRLAyx/7181oG9Ln+3/UrDVwm27uqpYrwn1rS8PFbCNbGe7x846fM4z7B/OHdbJdrL2",
	"Dof/sKnMuD+cl9AnNzge+tFhf2ze/L2gUrvKMNkbH/6j614zVH69OVtSyh8r1QJAwwUtCNLXCPgc4mu8",
	"1Yq3WWytZ4TMuW3Tw+49DUBsa533DhbXALXdT4MzWno/7M2KpTQHJ41tFmawbBKvegNWaMFSPDDHBH0S",
	"8pRGrtu7FoWsQ3AwBXnYAtvgrB7NWY/FfbiGqNCAX/uF6gFVujfaSBdyKTAe6f49WwyXkIo8A67J3vn0",
	"B5Li4+amk8HAPF0JpSf7w+EwuPlYHv7P3XFsFd6uFnG3CbPirwEAGpgQt0KN5e0VWhCCrhVsz779cj1I",
	"MuFM+SsC96ILl24+3vx3AAAA//8fdb8UqEgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
