// Package gimage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package gimage

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8w7a3PbtpZ/BcP2TpxcSqJkKdfWTGdHSRxHTZq6dtL2zk3WgkiIQkICLAjaVjP67zsH",
	"DxIUSUVuurv+YlkEeHBw3i998UKeZpwRJnNv+sUTJM84y4n68gxHl+SPguQSvoWcScLUvzjLEhpiSTkb",
	"fMo5g2fkDqdZQvTOiHjTcRD4HhGCC28KoJCF5XspyXMcE2/q/UYjuUZpkUu0JCjjOZX0hnhb38vDNUkx",
	"gPtekJU39b4bVKgO9Go+OAP4lwZpb7vd+l5E8lDQDJDzpt6c3eCERkjow1GGBU6JJCKHQ+ZMEsFwcqbR",
	"vP8lJ+4lLTR0RcQNEUhDda/7EtOEREhylAkekjxHNIWVv/O+Bodc46Bx25YHGMbKcP1zRgTWb33xMsEz",
	"IiTVjNdITb/swH6Gc/J03CMM7h5p1BEX6OoYfSYbz6/IoyHkg2zNJe9/ymLP9+Qmg5VcCspiuDF3Eaif",
	"VOKG1Fu+R1iRetP/gHzSP+FBHuIEPkPBM/jgaSZInqt/2Q0R0vvo4lO+18BCCYS6NY4iCmfi5MKhhhQF",
	"8bvQ6+UZCemKhq5c+a6YrAmN19KbPgVBuQVp96YnQbAtMeHLTySUikMgo1SQCC5aEcc37ChR/dh419cc",
	"dZS1zs8QJ8kSh5+vC5G0EVvfGt2S5Zrzz+j95Ru04gIBUROi2MC4hGtajCrCrqXM8ulgkG5wlvVDng4M",
	"FM/3VlykWHpTrxB0rwDkTaTe0FwivkLVHqU1RABQoIkkmmv7tGVHzre+l+K7uX5zCAxJKbNfS/ywEHjT",
	"zY+99Dd62WDAEpavadS853tG/ygIUhsQjQgDOhNRo7Fa7A1Hx+PJ03+dnAZttBQkLxLZQshLvaAYSnC4",
	"RjXJOoSKcxC/yubsEsr3collkbfZC7iUsXSUxchsrNS5WjM6nBBJIhAdZSjrOuyuN+6vQbcLOMiz5Chc",
	"k/CzoXSFSQl+oFYGXyf2toX/z4396VRBqwu7uL3DIiYS6WV0xI0u+ijFlElMWY64oDEF/aQr0ENkbA6J",
	"HjuU1Db2U0bgI1P0vCXLrE7BDkP8V819A9AfBU6o3GhQK1wk0pueTHatp6UV2BXzBjoa9kAh0ZrGayLQ",
	"D2hJpCTiscshgJTiO5rCja36mm8lMpRJEhNhVEKJ7HVFe0utpboauJFjJTIf25jsqr8m0cdWzit308n4",
	"v42433Qd35NK0K675PAFyeGuiBcyK6w8uprKtHw5UhbTlZUy35N0tdIfnu8t0x3Bs5sOoPEupq00Fzzr",
	"JLj1uLs3hJeQXkSUoYzekaRmAZ5+XaQeCjNNINF6RbXWfsOTr9/wrgn1dxRyLiLKsCTgkiXPeglZSRRy",
	"wequqq6VQdsBm+YB//4bD+iQqTsPTraE862QtAlXPcRuxlIq7t+9wqt37y6MU0Fqh4OzSoSahCA256hD",
	"UseXYW+pQfUEqiEQZYrR1Gupcw51HLL7XNA2RdJiW2r+AV7vnDCIJUinLmLwVfJaxRtN3GZqFalVFZ+c",
	"E2AtOkYXgqMjnKhUBhJCcN8QwD/uo7N+3PfRo+F0+Ag+nk5P4fN0OnwKn+PpMXwcT8ePaneEfZ2u71rl",
	"Bg303uqjNVkEyXlSqFi4gSlnyaaProos40Lm6NHwNeAwgr9coEfj14/UO+YqRQa5C2Vx3zGvw9ee743g",
	"z/h13XSqh01+84i0RDqzOVIrQK8iV8xEsWaSCdzNebHCvzfqT3qrBOfrnlWUciEwC5kgN5Tc6g29GjCz",
	"97iXCW7WzW5nsT90T3A2qO+sd9wPLFTSC4JRtTJ2/q1vGtZXVjiXe5aLRAq8u45T/CdnfcZvcC/E7Abn",
	"vZvhFKK9WPDPClnKSEWWxsOeDXZq3NpLkgYXGYmVTFxngqdZi886S0gKsTjwE99wUFKG5NoIZU3CM8Kz",
	"hPhIkjvpo1ssiUixgDQsxXdvCIvBYQwDxxY5OXDH8e/InUTOI2Wc7emAkyVqDROM8oLlRCJ+QwRKeaHj",
	"2Domo8BY8hK1w7xkHcELQVZEQNxitzYjlxZ/WuFqnrUlFIS0pGuXmEU8RbColEuQTPCoCOkyUTZCpVpH",
	"gV5Te2sh7HjkZMWUSYXXfn9Z2SYTUHvDYDS+gz9eo/ij+BLRlLBcpcxHv81fvHt19+psfv7q3eO6RXSg",
	"ZBiCbYDw3x8+RP+8gz/ft2dZm6TFUupz1eIAk1yuiaShGzyuueSC4ITmegELWf7LaErqTGls3x83Gult",
	"8+WvCE7knrwcZ3RP6aeKyfANpgleqooT4/I65GxF40KoXLRg1XJbsFan1ZUOEvgKzeaqSEdDslMz0kYE",
	"NMk5FpIMcld72OaSu3Lxn2+IwEliT2ym4mtFqo2SqVjgyFzNPq4xqNrbuOwNEXlrSW92MUd20YUV9If9",
	"4WHhRr0QcXCKPa/HNY6csdZ0uCuB0HD2ZRCgTt+aNkRYYnQE9iNPgWG6klrXXfrrs58vb4PX5zGfzWaz",
	"t1fv12fvY/j3DP48ez77d7/fb48TJYYT9gn9VwR4Vr6GSmhtgnh8DblP49I6J9L1xTWmjLLYKfK1FZGr",
	"WkwPL8N+B9eMJW9zETmNGYkgG3t/+UbTNoEc09DWRzr+fRqglLLHreXNWPvyXHKBY9LPj/s6gMC3uSp6",
	"OqhaJP/r994s/bOnGfG1UihY+evlRpK8U35pQlQMDKKndzqITkbj0clJi3NpCmNH7qhP2ZM8tgt3m55e",
	"qmL7vRN0Uwr7eoru1ID+91L2+/Uy7pfPu6Vds3hoim+I9NUk/x406kiZD0iVr0KcdPN5hUPZluFe6fQH",
	"6XV0FPQn6Ae0xsnKR6N+gH5AES+WCalpYtCfONKtN3i1e7qBVD+o7smKdPmQqjcd5DbU+tjWGMpJWAgq",
	"N1fhmqSauLOMviabWdEmI+BqrY3FhVwTJk3rBh2VkQsID2w8x5Lc4g0QmzLt2yNVc2E4BTR+780u5r3X",
	"LiGwOlt3Hylbcds4xaEihXnxXBPSpMUQTIB5diyqXBdLZTxxJkiOqTGyLR5n3sv4LRElc6osFGEWuR0G",
	"uJHdu9ygc87jhJhs3Ue/qhgKzea+em/22xV6RiLBw8/9D+wD++479JJgWQiSf2A99OTJbI60WTwvD3zy",
	"ZIqeC4Kl9R5oJXiqsi5UKBRMaWDUn6CXkPj6tWKBg4SGzdBYlQkcZNBbfoPRc5WVakQ0FhflPQELbWV9",
	"pDqhPgoFz3xk+6D6gqYVajDVoHRTpmyK5QDKAEZpkUiaJeXVQs7CQgjCZLLRb79MyJ3KdWwYBq9fOYEK",
	"wjnSOuDXnCw8vzpGWemN31++yQ3RZzUZ/cCe2zN9lW0CT4uc5IiwGyo4g4y4B2dEO9LdRy+5QDohU8IR",
	"kSzhG5VB+x8YjiJkVWNHLW4odpWh/wFi1ISGxASaRqR/mr87XI4Hy4QvBymmbPBm/vzs7dWZCtipTBzt",
	"mF3MPSdo9ob9Uf/pU9McZTiDLOC4H/SPdZa2Vrqve1TK4PK8NSv+OjvRLZVrFNHVisADJwRTqvDkidFb",
	"EjlL0ydPQAwWupu+sDKIJHeSTrVDCeViipSHAE3U5k2tgaQuQIt4hgSJFcvhsRFdWDL/aiRNocVsUhKt",
	"9mjZ1iYYcJ4lidsuxoJYy0BU3STDkAGRxOopRzEXvJCUkVxzvHx7Htn2paGlp402yeUzHm0OnxRR/Erp",
	"HYmu693uvEhTLDYgVJZLtSj4BieFEj33tf+U7aRaUDI0UYkzUFENPFTzDV2jCFu/HezIhNouWGfOogJc",
	"umXT5inbgCeTTuDHLTibWY4mxrpsZVDWX+5UuWTjTYPt9uN2e/AATW1QYlt3xlIUxPHuCoVREBzA7Xud",
	"3T2802iYVy3vre+NNSptJ5QoD5yZra3vTQ55pT4EpUhZCmeHKVFduhgkUuPsfYTXBqV0dJqmUrMxq6qI",
	"gkRF6GY4Su1tpILB3RiRMrbpF9M1zomUlMWlXVJN5MUU/Xhxdj74jSwvqv7yTmPZLhgnJdThjwHIC11n",
	"m6LFyWSBjmLOI7TECWahXr8kIU9TwiISwZ6gdxosVKR1S5Y+WpwGvdOJfpAJymSLXbE0mJvI768bFrjU",
	"tdN0r/j2isal4SyDAl16KS1LqZZVNUEnqyXE00lLrGsjW+D4LVle80zS1BQpKwR+Nk8tadyDS0jaBOyY",
	"B8WQnptt1ezJwZq+O5Lxf6zsO1MzLZN6Svwtb0iE8iIEXVsVSbL5/9L3Uj+rZrxW8yr2LHVdj9ntUXXt",
	"oEtNXxJ5Swhzgg4tCM2Iwzy3ap2xeDFFF1xIZQveEnnLxWd0LnC2pmGOjnLbepMCszzDgrBwo7R18SmL",
	"Fz58kNgYBnSU8Dzf+Ijxlv0xXS2mFWhFq3CNWUwguFQzOglNKWAZ8oSL3G8BAn5wMUXKAh2lPCKCgQ6Y",
	"e/m6skeEMna5fkXS1QoQler8dziOSWSSj5dgF1+aMKeHFssUgD+jMsVZq3lRdP926yL5NehfTa0tUyVX",
	"tDzInDQtSFX1qA+lKIOgSkr8WsUSXWcDZVvPdks1plC4c4SCey8zUpvveahWRCH5YIyIk3Y6AwWdpgTi",
	"vm47AnkCRoKEErO4SLAwWYPOvK15MUbkeTlJUpqPO9CrDWhVfa4E8ZXKmi24o8APEM2r8RO+0qCNUkP4",
	"CaB0VLqYohdVo60Oqk0rBc++XSVDAmS/tgRzSA6H61WDg6setci/VVe0o62SAhVgq2Gbjfq8j8I4w1kP",
	"VFsEz7KHoivAOCcSNqzr1JWy496pL3YoBzRjNrdKqFRFl6nchr5NhbvKZPXClNGxn3hEkhzNbCPSKJp+",
	"fYoW7cMlC3T0fdAPjk91s+SxX27smBExL4wnve+D/nAyHBgyUVvdq2ZyXGDN0QsNaHg8BkCjsYbj23mc",
	"8Wul3+Wlp2hhh0csBhXGHUMrOxsBnkO2KVp0jJvY9wCx4KR8G4hsxdh4/tKaad+5mJrgQLULy9I1M7U3",
	"3eQyZZ8PRRAch2gyHL1+pk2ZjuAhptptjulOGLysu2GFJLnTMbMwH7dYOCt3327lcHQD6VZUN3Ez81Rn",
	"h3pQulYpMTNR3bNNjXGb2tCMV83BeKtCFkJNH6AQMih15CrZqJwci9zbkxfZ0ZHxyA5v1GYtzAjF7pCD",
	"sgrUTgBUt75Sz+pDXOWNS3y7Rm7uYbZ3Z/n+NtPtctYEfrUb6vZLNcBz5PS9H7emjTqwq4pDo7HfFn12",
	"tcbhc/UyvPoR/nnxPjn75dfL8Sh9+/mfP53+8uJ29mIdn89++3R5im/VKz9evp+cic8/xnH8ww9evVdr",
	"+65lbWo03taa0Q4ntYZV93TK44fccxSMT6q2+t7muD3+r7Sv68BqTWz34qPg9F/Dyai8OWB3D2k70FNb",
	"G/swfHXpWR2fqjyq0cPKbVf9IuO29cSMHu5pi3HVT1NmF3OkN6rujRn0oaqGU58XUo74kshCsNyOHfPV",
	"tPLCCtYRhaiUqB8V4SRH1dRS3ePt39gw9HqoSqHsfbNFwElyXU001Q1+ksA1clQbg7JaYke3ltrH7kxL",
	"3WOEyk5MOVNNzX7M1oK85izZqbUZiquFvQg2Jsf2Y7mz/WBUD1bCnem4Fi28MtNiNEf2yLpKaBD6p1WO",
	"/OvHRvZNK6IzYDVNJLciTO5waIccQBXMTIiOVtc0XtvpW/QGs/BPnoNZBaGiLDZB6pxVv2OxwVPnwBUs",
	"2sEk0GoVOHJQKiv5LXqg8f72cEc7xWsKCNcly1DGxHQ2jPlKWnfobNieskytOQTepBu3q+NuvIbBSTPf",
	"bHVYe4Ip61lPR/dJQusjSA8zDdV68TBcm+FmqYDl75qrvu6+rFT/GrtTw3UXuCoEbxC2HSXbgdf9YaO7",
	"Z0Y7bM4T9CcLMyKkG0RHk+AfOpUZ9YNFOTFkFkeBXQ36I/XmHwUW0hRc0dFo8o82v6aw/HZ11qiUvylx",
	"AkBFBckR4FcL+Myg1KhTi7s01mnFAHH2HTppP1PNVXWWT++hcbVZsIepcEpKH4a+abaU6mC40aVhagRM",
	"gKtXMwCNaQ8776KCPkGyBIemibrhhXAnWyAFedyYYYFdPZzRHo365I6EhSTwtV/kPYJz2RvupAuZ4BCP",
	"NH6zz0OcoIjckIRnKWESHV3NfkIJPK4fOh0M1NM1z+X0OAgCb/uxvPyXw8e/qjE1J+JuIqbZ7/TVa6MW",
	"BoJD8iaERme+DYJuhTdfdoMkFc6Uw/fmRRMubT9u/ycAAP//S4/wu5BFAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
